### PR TITLE
Fix weblate merge conflict

### PR DESCRIPTION
**Pull request by rimrul**

### CODE REVIEW

**Comment by rimrul** [comment]
Ok, that worked.

**Comment by jnavila** [comment]
Yes, you have to be careful when editing the po on both sides at the same time. Po files are not really friendly with simple merging.

BTW, I passed your po file through https://github.com/flashcode/msgcheck and there were some warnings. I use this script for French; do you think it could apply to German?

**Comment by jnavila** [comment]
Another point: now, I'm going to push the compiled files to git-html-l10n in order to being published to git-scm.com. 

After that, I'll update all the sources to v2.23.0. This may create some fuzzy matches.

**Comment by rimrul** [comment]
> BTW, I passed your po file through https://github.com/flashcode/msgcheck and there were some warnings. I use this script for French; do you think it could apply to German?

Yes, I think I can do that. There seems to be some overlap with weblates quality checks, so this might reduce the amount of quality checks I'll trigger in the future.

>After that, I'll update all the sources to v2.23.0. This may create some fuzzy matches.

That's ok. I was thinking of following your suggestion from #22 after the language update and then removing the collective fuzzyness from `documentation.de.po` anyways. It's already the most fuzzy translation we have.

**Pull request merged**
