### PR TITLE
 translate date-formats.txt to german 

### PR DESCRIPTION
**Pull request by rimrul**
Getting this to turn out the way I wanted was a bit of a struggle, but I've got it in the end.

### CODE REVIEW

**Comment by rimrul** [comment]
I've had some trouble getting all depedndencies for the `bundle exec make all` set up and when I did, I had missed the fact that it only produces man-pages that are at least 80% translated by default. When I modified that, it changed the pot-date, changed the wrapping on long messages, marked most of my translations as fuzzy again and removed the `ignore-translated` tags. But it's all good now. I'll write up the packages I was missing for future contributors.

**Comment by jnavila** [comment]
Thanks for the feed-back, this is very valuable. I had most of the points you raised in mind, so your message is a confirmation that many changes are badly needed.

> I've had some trouble getting all depedndencies for the `bundle exec make all` set up and when I did, 

This is a proposed way of building the pages, but you could also directly install asciidoctor. On linux distros, this is quite a standard package; on MacOSX, this is also available with brew; on Windows, I guess you have to use `bundle`. Here `bundle` is used in a general scheme to make sure to have repeatable output with known versions of selected tools.

> I had missed the fact that it only produces man-pages that are at least 80% translated by default.

I had in mind of writing a small help guide for translators about how to handle this. Indeed, the 80% rule is a rule that should encourage to fully translate a manpage before starting the next one.

>  When I modified that, it changed the pot-date, changed the wrapping on long messages, marked most of my translations as fuzzy again and removed the ignore-translated tags.

I have searched for some known canonical format of po files that fits with version control, but it seems there's nothing like this. If I can come up with a workable solution, I'll add a check to the continuous compilation.

>  But it's all good now. I'll write up the packages I was missing for future contributors.

Thanks for taking this up.

**Comment by rimrul** [comment]
I've needed the following additional packages on Ubuntu bionic: `python3-polib gettext patch ruby-dev zlib1g-dev liblzma-dev ruby-bundler`

I've tried installing `polib` via pip, but that didn't work for me. Also I needed to install this perl module from CPAN: `cpan -i Unicode::GCString`

**Comment by jnavila** [comment]
For Unicode::GCString, the package is libunicode-linebreak-perl

**Pull request merged**
