### PR TITLE
Unfuzzy German translation

### PR DESCRIPTION
**Pull request by rimrul**
I'm working on fixing most of the fuzzyness of `po/documentation.de.po`. I'll definitely try to get this completed before 2.24.

E: Currently about 200 fuzzy entries fixed (as of 2019-10-01).

### CODE REVIEW

**Comment by jnavila** [comment]
Still work in progress? Should we merge?

**Comment by rimrul** [comment]
Yeah, I'll fix up the `git add -i` commit tomorrow and mark it ready to merge.

**Comment by rimrul** [comment]
It's only about a third of the fuzzy strings, but it should be good to merge.

**Comment by rimrul** [comment]
Weblate doesn't seem to update it's count for fuzzy strings from Github properly. It still says 820, even though searching all occurences in the file only results in 558 matches. And some of those 558 are obsolete strings aka false positives. I'll raise an issue with weblate, because I don't think that's intentional.

**Pull request merged**
