### PR TITLE
Add UK translations: git-annotate and related

### PR DESCRIPTION
**Pull request by burlakvo**
Add Ukrainian translation for strings related to `blame-options`, `line-range-format`, and `git-annotate`

### CODE REVIEW

**Comment by jnavila** [comment]
Hello @burlakvo , 

I do not know how you edited your po file, but there's at least a syntax error in it at line 289 where the double-quote characters are not escaped.

**Comment by jnavila** [comment]
Another remark: all the commits must be signed off by their author. That's done by adding "Signed-off-by:" trailer to the commit message. See https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---no-signoff for more details.

Thank you

**Comment by burlakvo** [comment]
Finally figured it out with Ruby, so tested it normally. Translation fixed, improved, and added new for `line-range-format` related strings.

Forgot about "signed-off-by", I will fix it soon

**Comment by burlakvo** [comment]
Signed off

**Pull request merged**
