### PR TITLE
Create python-publish.yml

### PR DESCRIPTION
**Pull request by RZ7272**

### CODE REVIEW

**Comment by jnavila** [comment]
What's this PR for? It looks like an automatically generated.

**Comment by hoosam75** [comment]
[](url)

**Comment by hoosam75** [comment]
> What's this PR for? It looks like an automatically generated.

r1372:master

**Comment by hoosam75** [comment]
> _لم يتم تقديم وصف._

**Comment by hoosam75** [comment]
r1372:master

**Pull request closed without merging**
