### PR TITLE
Add zh_HANT translator information

### PR DESCRIPTION
**Pull request by waywayfox**
Hi, I'm going to start the translations of Traditional Chinese.
I add my information at the documentation.zh_HANT.po.
 
I'm not familiar with weblate, so I'm wondering if there have some way to synchronize my local repository and the .po that generate by weblate.

Many thanks

### CODE REVIEW

**Comment by rimrul** [comment]
You can add weblate as a remote to your repo and pull from there. I'll dig out the URL.

**Comment by rimrul** [comment]
`git remote add weblate https://hosted.weblate.org/git/git-manpages/translations/`

**Comment by waywayfox** [comment]
thank you very much, I will try it later.

**Comment by jnavila** [comment]
OK, please start translating before we merge your branch.

**Pull request closed without merging**
