### PR TITLE
Unfuzzy some more german translations

### PR DESCRIPTION
**Pull request by rimrul**
I've rebased my changes onto weblate/master to avoid merge conflicts.

### CODE REVIEW

**Comment by rimrul** [comment]
Will rebase onto current master.

**Comment by jnavila** [comment]
When can you make it land?

**Comment by rimrul** [comment]
Landed

**Comment by jnavila** [comment]
Thanks. Hopefully, I will update the project to git v2.25.0 today.

**Comment by radinmoradi** [comment]
در تاریخ سه‌شنبه ۲۸ ژانویهٔ ۲۰۲۰،‏ ۱۱:۰۶ Jean-Noël Avila <
notifications@github.com> نوشت:

**Pull request merged**
